[package]
name = "_test"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["debug"] }
simple = { path = "../crates/simple" }

[profile.release]
lto = true
strip = true
opt-level = "z"